### ISSUE TITLE
Compatibility with Datatable 1.10.2

### ISSUE THREAD

**Issue by hariawan** [eherve/mongoose-datatable#25]
Hi, I've a problem with my codes.
Here's my codes https://gist.github.com/hariawan/7bad74f32a42a06d3a57

There's no error, I think the problem in the render part.
Can you help me?

- Datatable 1.10.2
- Mongoose ^3.8.13

**Comment by eherve** [comment]
New version 1.0.0 is compatible with DataTable 1.10
