### ISSUE TITLE
Sort column doesn't work in new 1.0.0 version

### ISSUE THREAD

**Issue by hepr** [eherve/mongoose-datatable#29]
Hi,

I upgrade your module form 0.4.2 to 1.0.0 with datatable 1.10.5 and I see that columns ordering doesn't work :-(

I see in your code reference to sortable but in 1.10 this parameter was named orderable. Is the problem ?
Thank for your help

Herve

**Comment by eherve** [comment]
Hi,

Where do you see the reference to "sortable" ?
The code check if the field is sortable in field.js:
<pre>
...
var QUERY_COLUMNS = 'columns';
...
var QUERY_SORTABLE_PREFIX = 'orderable';
...
 function isFieldSortable(query, index) {
   return query[QUERY_COLUMNS][index][QUERY_SORTABLE_PREFIX] == 'true';
 }
</pre>
Then it checks if it is used in sort and what is the direction in searchCriteria.js

can you activate the debug and send me the trace please ?

Regards,

**Comment by hepr** [comment]
Hi,

this is my debug :

{ draw: 1,
  columns:
   [ { data: 'bool',
       name: '',
       searchable: true,
       orderable: false,
       search: [Object] },
     { data: 'name',
       name: '',
       searchable: true,
       orderable: true,
       search: [Object] },
     { data: 'code_client',
       name: '',
       searchable: true,
       orderable: true,
       search: [Object] },
     { data: 'commercial_id.name',
       name: '',
       searchable: true,
       orderable: true,
       search: [Object] },
     { data: 'zip',
       name: '',
       searchable: true,
       orderable: true,
       search: [Object] },
     { data: 'town',
       name: '',
       searchable: true,
       orderable: true,
       search: [Object] },
     { data: 'idprof3',
       name: '',
       searchable: true,
       orderable: true,
       search: [Object] },
     { data: 'Status',
       name: '',
       searchable: true,
       orderable: true,
       search: [Object] },
     { data: 'prospectlevel',
       name: '',
       searchable: true,
       orderable: true,
       search: [Object] },
     { data: 'datec',
       name: '',
       searchable: true,
       orderable: true,
       search: [Object] } ],
  order: [ { column: 1, dir: 'asc' } ],
  start: 0,
  length: 10,
  search: { value: '', regex: false },
  bChunkSearch: true }
Query: { draw: 1,
  columns:
   [ { data: 'bool',
       name: '',
       searchable: true,
       orderable: false,
       search: [Object] },
     { data: 'name',
       name: '',
       searchable: true,
       orderable: true,
       search: [Object] },
     { data: 'code_client',
       name: '',
       searchable: true,
       orderable: true,
       search: [Object] },
     { data: 'commercial_id.name',
       name: '',
       searchable: true,
       orderable: true,
       search: [Object] },
     { data: 'zip',
       name: '',
       searchable: true,
       orderable: true,
       search: [Object] },
     { data: 'town',
       name: '',
       searchable: true,
       orderable: true,
       search: [Object] },
     { data: 'idprof3',
       name: '',
       searchable: true,
       orderable: true,
       search: [Object] },
     { data: 'Status',
       name: '',
       searchable: true,
       orderable: true,
       search: [Object] },
     { data: 'prospectlevel',
       name: '',
       searchable: true,
       orderable: true,
       search: [Object] },
     { data: 'datec',
       name: '',
       searchable: true,
       orderable: true,
       search: [Object] } ],
  order: [ { column: 1, dir: 'asc' } ],
  start: 0,
  length: 10,
  search: { value: '', regex: false },
  bChunkSearch: true }
Search Criteria builded: { options: {},
  pageStart: 0,
  pageSize: 10,
  nbColumns: 10,
  search: undefined,
  fields:
   [ { index: 1,
       path: 'name',
       searchable: false,
       search: undefined,
       sortable: false,
       sort: undefined,
       selectable: true,
       type: 'String',
       ref: undefined,
       refType: undefined,
       arrayType: undefined,
       base: undefined,
       arrayPath: undefined },
     { index: 2,
       path: 'code_client',
       searchable: false,
       search: undefined,
       sortable: false,
       sort: undefined,
       selectable: true,
       type: 'String',
       ref: undefined,
       refType: undefined,
       arrayType: undefined,
       base: undefined,
       arrayPath: undefined },
     { index: 3,
       path: 'commercial_id.name',
       searchable: false,
       search: undefined,
       sortable: false,
       sort: undefined,
       selectable: true,
       type: 'String',
       ref: undefined,
       refType: undefined,
       arrayType: undefined,
       base: undefined,
       arrayPath: undefined },
     { index: 4,
       path: 'zip',
       searchable: false,
       search: undefined,
       sortable: false,
       sort: undefined,
       selectable: true,
       type: 'String',
       ref: undefined,
       refType: undefined,
       arrayType: undefined,
       base: undefined,
       arrayPath: undefined },
     { index: 5,
       path: 'town',
       searchable: false,
       search: undefined,
       sortable: false,
       sort: undefined,
       selectable: true,
       type: 'String',
       ref: undefined,
       refType: undefined,
       arrayType: undefined,
       base: undefined,
       arrayPath: undefined },
     { index: 6,
       path: 'idprof3',
       searchable: false,
       search: undefined,
       sortable: false,
       sort: undefined,
       selectable: true,
       type: 'String',
       ref: undefined,
       refType: undefined,
       arrayType: undefined,
       base: undefined,
       arrayPath: undefined },
     { index: 7,
       path: 'Status',
       searchable: false,
       search: undefined,
       sortable: false,
       sort: undefined,
       selectable: true,
       type: 'Mixed',
       ref: undefined,
       refType: undefined,
       arrayType: undefined,
       base: undefined,
       arrayPath: undefined },
     { index: 8,
       path: 'prospectlevel',
       searchable: false,
       search: undefined,
       sortable: false,
       sort: undefined,
       selectable: true,
       type: 'String',
       ref: undefined,
       refType: undefined,
       arrayType: undefined,
       base: undefined,
       arrayPath: undefined },
     { index: 9,
       path: 'datec',
       searchable: false,
       search: undefined,
       sortable: false,
       sort: undefined,
       selectable: true,
       type: 'Date',
       ref: undefined,
       refType: undefined,
       arrayType: undefined,
       base: undefined,
       arrayPath: undefined } ],
  select:
   { name: 1,
     code_client: 1,
     'commercial_id.name': 1,
     zip: 1,
     town: 1,
     idprof3: 1,
     Status: 1,
     prospectlevel: 1,
     datec: 1 },
  sort: {},
  conditions: undefined,
  populate: [] }
Data: { draw: 1,
  recordsTotal: 4988,
  recordsFiltered: 4988,
  data:
   [ { _id: 5220c606269148e7260002ac,
       Status: 'ST_PFROI',
       commercial_id: { name: 'Demo Demo' },
       datec: Thu Jul 08 2010 22:48:18 GMT+0200 (CEST),
       name: 'Prospector Vaalen',
       prospectlevel: 'PL_HIGH',
       town: 'Bruxelles' },
     { _id: 5220c606269148e7260002ad,
       Status: 'ST_PFROI',
       commercial_id: { name: 'achille' },
       datec: Fri Jul 09 2010 00:15:09 GMT+0200 (CEST),
       name: 'Swiss customer supplier',
       prospectlevel: 'PL_LOW',
       town: 'Geneva',
       zip: '1201' },
     { _id: 5220c606269148e7260002b3,
       name: 'From Island and Co',
       zip: '78180',
       town: 'Nevers',
       code_client: 'CU1108-0002',
       datec: Mon Aug 01 2011 02:31:24 GMT+0200 (CEST),
       commercial_id: { name: 'demo' },
       Status: 'ST_NO',
       prospectlevel: 'PL_LOW' },
     { _id: 5220c606269148e7260002b4,
       Status: 'ST_CREC',
       code_client: 'CU1108-0003',
       commercial_id: { name: 'Demo Demo' },
       datec: Mon Aug 01 2011 02:31:43 GMT+0200 (CEST),
       name: 'ProCust company',
       prospectlevel: 'PL_NONE',
       town: 'mmm',
       zip: '78180' },
     { _id: 5220c606269148e7260002b5,
       Status: 'ST_CINF3',
       code_client: 'CU1108-0004',
       commercial_id: { name: 'admin Admin' },
       datec: Mon Aug 01 2011 02:41:26 GMT+0200 (CEST),
       name: 'FFF SARL',
       prospectlevel: 'PL_NONE' },
     { _id: 5220c606269148e726000313,
       Status: 'ST_CFID',
       commercial_id: { name: 'Demo Demo' },
       datec: Tue Feb 12 2013 01:15:37 GMT+0100 (CET),
       name: 'TEST',
       town: 'PETIT-ENGHIEN',
       zip: '7850' },
     { _id: 5220c606269148e726000332,
       Status: 'ST_CFID',
       commercial_id: { name: 'Demo Demo' },
       datec: Tue Feb 12 2013 15:50:50 GMT+0100 (CET),
       name: 'Tartampion' },
     { _id: 5220c606269148e726000316,
       Status: 'ST_PCHAU',
       code_client: 'C-MAO',
       commercial_id: { name: 'Demo Demo' },
       datec: Thu Jan 01 1970 01:00:00 GMT+0100 (CET),
       name: 'Maore',
       prospectlevel: 'PL_NONE',
       town: 'MAMOUDZOU',
       zip: '97600' },
     { _id: 5220c606269148e726000317,
       Status: 'ST_CFID',
       commercial_id: { name: 'Demo Demo' },
       datec: Tue Feb 12 2013 07:39:10 GMT+0100 (CET),
       name: 'Dupontel Albert',
       prospectlevel: 'PL_NONE',
       town: 'Boninne',
       zip: '5430' },
     { _id: 5220c606269148e72600031b,
       Status: 'ST_CREC',
       code_client: 'DEMO',
       commercial_id: { name: 'Demo Demo' },
       name: 'bla sarls avec',
       prospectlevel: 'PL_NONE',
       town: 'bla',
       zip: '12345' } ] }
{ draw: 1,
  recordsTotal: 4988,
  recordsFiltered: 4988,
  data:
   [ { _id: 5220c606269148e7260002ac,
       Status: 'ST_PFROI',
       commercial_id: [Object],
       datec: Thu Jul 08 2010 22:48:18 GMT+0200 (CEST),
       name: 'Prospector Vaalen',
       prospectlevel: 'PL_HIGH',
       town: 'Bruxelles' },
     { _id: 5220c606269148e7260002ad,
       Status: 'ST_PFROI',
       commercial_id: [Object],
       datec: Fri Jul 09 2010 00:15:09 GMT+0200 (CEST),
       name: 'Swiss customer supplier',
       prospectlevel: 'PL_LOW',
       town: 'Geneva',
       zip: '1201' },
     { _id: 5220c606269148e7260002b3,
       name: 'From Island and Co',
       zip: '78180',
       town: 'Nevers',
       code_client: 'CU1108-0002',
       datec: Mon Aug 01 2011 02:31:24 GMT+0200 (CEST),
       commercial_id: [Object],
       Status: 'ST_NO',
       prospectlevel: 'PL_LOW' },
     { _id: 5220c606269148e7260002b4,
       Status: 'ST_CREC',
       code_client: 'CU1108-0003',
       commercial_id: [Object],
       datec: Mon Aug 01 2011 02:31:43 GMT+0200 (CEST),
       name: 'ProCust company',
       prospectlevel: 'PL_NONE',
       town: 'mmm',
       zip: '78180' },
     { _id: 5220c606269148e7260002b5,
       Status: 'ST_CINF3',
       code_client: 'CU1108-0004',
       commercial_id: [Object],
       datec: Mon Aug 01 2011 02:41:26 GMT+0200 (CEST),
       name: 'FFF SARL',
       prospectlevel: 'PL_NONE' },
     { _id: 5220c606269148e726000313,
       Status: 'ST_CFID',
       commercial_id: [Object],
       datec: Tue Feb 12 2013 01:15:37 GMT+0100 (CET),
       name: 'TEST',
       town: 'PETIT-ENGHIEN',
       zip: '7850' },
     { _id: 5220c606269148e726000332,
       Status: 'ST_CFID',
       commercial_id: [Object],
       datec: Tue Feb 12 2013 15:50:50 GMT+0100 (CET),
       name: 'Tartampion' },
     { _id: 5220c606269148e726000316,
       Status: 'ST_PCHAU',
       code_client: 'C-MAO',
       commercial_id: [Object],
       datec: Thu Jan 01 1970 01:00:00 GMT+0100 (CET),
       name: 'Maore',
       prospectlevel: 'PL_NONE',
       town: 'MAMOUDZOU',
       zip: '97600' },
     { _id: 5220c606269148e726000317,
       Status: 'ST_CFID',
       commercial_id: [Object],
       datec: Tue Feb 12 2013 07:39:10 GMT+0100 (CET),
       name: 'Dupontel Albert',
       prospectlevel: 'PL_NONE',
       town: 'Boninne',
       zip: '5430' },
     { _id: 5220c606269148e72600031b,
       Status: 'ST_CREC',
       code_client: 'DEMO',
       commercial_id: [Object],
       name: 'bla sarls avec',
       prospectlevel: 'PL_NONE',
       town: 'bla',
       zip: '12345' } ] }

I see sortable line 146.

Thank you for your help

Herve

Herve Prot

President LE&CO
2 rue des Faubourgs
F-63960 Veyre-Monton
Tel : +33 6 76 76 17 65
herve.prot@leandco.fr


2015-03-24 16:32 GMT+01:00 Eric HERVE <notifications@github.com>:

**Comment by eherve** [comment]
Merci pour le debug,

ligne 146 du fichier searchCriteria.js fait référence au getter sortable des fields défini dans le fichier field.js
ce getter:
<pre>
  Object.defineProperty(this, "sortable", {
    writable: false, enumerable: true, value: sortable });
</pre>
ce getter retourne si le field est sortable et cela est défini par dataTable.

Dans les traces on voit que le tri se fait sur la première colonne <pre> order: [ { column: 1, dir: 'asc' } ],</pre> hors cette colonne est marqué comme non sortable <pre> [ { data: 'bool',
       name: '',
       searchable: true,
       orderable: false,
       search: [Object] },</pre>

Cordialement,

**Comment by hepr** [comment]
Merci de ce retour.

C'est ma colonne 0 qui n'est pas orderable.
Quand je fais le test sur d'autres colonnes ca ne marche pas non plus.
Ci-joint les traces sur la colonne 4

Quand je regarde le debug, dans query (autre que la colonne 0) j'ai
searchable a true et orderable a true et dans le searchCriteria searchable
est false et sortable est false. Ca n'a peut etre aucun rapport avec mon
probleme.

Query: { draw: 1,
  columns:
   [ { data: 'bool',
       name: '',
       searchable: true,
       orderable: false,
       search: [Object] },
     { data: 'name',
       name: '',
       searchable: true,
       orderable: true,
       search: [Object] },
     { data: 'code_client',
       name: '',
       searchable: true,
       orderable: true,
       search: [Object] },
     { data: 'commercial_id.name',
       name: '',
       searchable: true,
       orderable: true,
       search: [Object] },
     { data: 'zip',
       name: '',
       searchable: true,
       orderable: true,
       search: [Object] },
     { data: 'town',
       name: '',
       searchable: true,
       orderable: true,
       search: [Object] },
     { data: 'idprof3',
       name: '',
       searchable: true,
       orderable: true,
       search: [Object] },
     { data: 'Status',
       name: '',
       searchable: true,
       orderable: true,
       search: [Object] },
     { data: 'prospectlevel',
       name: '',
       searchable: true,
       orderable: true,
       search: [Object] },
     { data: 'datec',
       name: '',
       searchable: true,
       orderable: true,
       search: [Object] } ],
  order: [ { column: 4, dir: 'asc' } ],
  start: 0,
  length: 10,
  search: { value: '', regex: false },
  bChunkSearch: true }
Search Criteria builded: { options: {},
  pageStart: 0,
  pageSize: 10,
  nbColumns: 10,
  search: undefined,
  fields:
   [ { index: 1,
       path: 'name',
       searchable: false,
       search: undefined,
       sortable: false,
       sort: undefined,
       selectable: true,
       type: 'String',
       ref: undefined,
       refType: undefined,
       arrayType: undefined,
       base: undefined,
       arrayPath: undefined },
     { index: 2,
       path: 'code_client',
       searchable: false,
       search: undefined,
       sortable: false,
       sort: undefined,
       selectable: true,
       type: 'String',
       ref: undefined,
       refType: undefined,
       arrayType: undefined,
       base: undefined,
       arrayPath: undefined },
     { index: 3,
       path: 'commercial_id.name',
       searchable: false,
       search: undefined,
       sortable: false,
       sort: undefined,
       selectable: true,
       type: 'String',
       ref: undefined,
       refType: undefined,
       arrayType: undefined,
       base: undefined,
       arrayPath: undefined },
     { index: 4,
       path: 'zip',
       searchable: false,
       search: undefined,
       sortable: false,
       sort: undefined,
       selectable: true,
       type: 'String',
       ref: undefined,
       refType: undefined,
       arrayType: undefined,
       base: undefined,
       arrayPath: undefined },
     { index: 5,
       path: 'town',
       searchable: false,
       search: undefined,
       sortable: false,
       sort: undefined,
       selectable: true,
       type: 'String',
       ref: undefined,
       refType: undefined,
       arrayType: undefined,
       base: undefined,
       arrayPath: undefined },
     { index: 6,
       path: 'idprof3',
       searchable: false,
       search: undefined,
       sortable: false,
       sort: undefined,
       selectable: true,
       type: 'String',
       ref: undefined,
       refType: undefined,
       arrayType: undefined,
       base: undefined,
       arrayPath: undefined },
     { index: 7,
       path: 'Status',
       searchable: false,
       search: undefined,
       sortable: false,
       sort: undefined,
       selectable: true,
       type: 'Mixed',
       ref: undefined,
       refType: undefined,
       arrayType: undefined,
       base: undefined,
       arrayPath: undefined },
     { index: 8,
       path: 'prospectlevel',
       searchable: false,
       search: undefined,
       sortable: false,
       sort: undefined,
       selectable: true,
       type: 'String',
       ref: undefined,
       refType: undefined,
       arrayType: undefined,
       base: undefined,
       arrayPath: undefined },
     { index: 9,
       path: 'datec',
       searchable: false,
       search: undefined,
       sortable: false,
       sort: undefined,
       selectable: true,
       type: 'Date',
       ref: undefined,
       refType: undefined,
       arrayType: undefined,
       base: undefined,
       arrayPath: undefined } ],
  select:
   { name: 1,
     code_client: 1,
     'commercial_id.name': 1,
     zip: 1,
     town: 1,
     idprof3: 1,
     Status: 1,
     prospectlevel: 1,
     datec: 1 },
  sort: {},
  conditions: undefined,
  populate: [] }
Data: { draw: 1,
  recordsTotal: 4988,
  recordsFiltered: 4988,
  data:
   [ { _id: 5220c606269148e7260002ac,
       Status: 'ST_PFROI',
       commercial_id: { name: 'Demo Demo' },
       datec: Thu Jul 08 2010 22:48:18 GMT+0200 (CEST),
       name: 'Prospector Vaalen',
       prospectlevel: 'PL_HIGH',
       town: 'Bruxelles' },
     { _id: 5220c606269148e7260002ad,
       Status: 'ST_PFROI',
       commercial_id: { name: 'achille' },
       datec: Fri Jul 09 2010 00:15:09 GMT+0200 (CEST),
       name: 'Swiss customer supplier',
       prospectlevel: 'PL_LOW',
       town: 'Geneva',
       zip: '1201' },
     { _id: 5220c606269148e7260002b3,
       name: 'From Island and Co',
       zip: '78180',
       town: 'Nevers',
       code_client: 'CU1108-0002',
       datec: Mon Aug 01 2011 02:31:24 GMT+0200 (CEST),
       commercial_id: { name: 'demo' },
       Status: 'ST_NO',
       prospectlevel: 'PL_LOW' },
     { _id: 5220c606269148e7260002b4,
       Status: 'ST_CREC',
       code_client: 'CU1108-0003',
       commercial_id: { name: 'Demo Demo' },
       datec: Mon Aug 01 2011 02:31:43 GMT+0200 (CEST),
       name: 'ProCust company',
       prospectlevel: 'PL_NONE',
       town: 'mmm',
       zip: '78180' },
     { _id: 5220c606269148e7260002b5,
       Status: 'ST_CINF3',
       code_client: 'CU1108-0004',
       commercial_id: { name: 'admin Admin' },
       datec: Mon Aug 01 2011 02:41:26 GMT+0200 (CEST),
       name: 'FFF SARL',
       prospectlevel: 'PL_NONE' },
     { _id: 5220c606269148e726000313,
       Status: 'ST_CFID',
       commercial_id: { name: 'Demo Demo' },
       datec: Tue Feb 12 2013 01:15:37 GMT+0100 (CET),
       name: 'TEST',
       town: 'PETIT-ENGHIEN',
       zip: '7850' },
     { _id: 5220c606269148e726000332,
       Status: 'ST_CFID',
       commercial_id: { name: 'Demo Demo' },
       datec: Tue Feb 12 2013 15:50:50 GMT+0100 (CET),
       name: 'Tartampion' },
     { _id: 5220c606269148e726000316,
       Status: 'ST_PCHAU',
       code_client: 'C-MAO',
       commercial_id: { name: 'Demo Demo' },
       datec: Thu Jan 01 1970 01:00:00 GMT+0100 (CET),
       name: 'Maore',
       prospectlevel: 'PL_NONE',
       town: 'MAMOUDZOU',
       zip: '97600' },
     { _id: 5220c606269148e726000317,
       Status: 'ST_CFID',
       commercial_id: { name: 'Demo Demo' },
       datec: Tue Feb 12 2013 07:39:10 GMT+0100 (CET),
       name: 'Dupontel Albert',
       prospectlevel: 'PL_NONE',
       town: 'Boninne',
       zip: '5430' },
     { _id: 5220c606269148e72600031b,
       Status: 'ST_CREC',
       code_client: 'DEMO',
       commercial_id: { name: 'Demo Demo' },
       name: 'bla sarls avec',
       prospectlevel: 'PL_NONE',
       town: 'bla',
       zip: '12345' } ] }



Herve Prot

President LE&CO
2 rue des Faubourgs
F-63960 Veyre-Monton
Tel : +33 6 76 76 17 65
herve.prot@leandco.fr

**Comment by eherve** [comment]
L'appel ajax de dataTable est paramétrée en mode POST ou en mode GET ?

Je vois d'ou vient l'erreur, dans le fichier field.js la comparaison de orderable est fait sur une string 'true' alors que normalement on est sur un boolean. Je pense que l'appel dataTable en mode GET envoi un string (comme dans le test du module) et que le mode POST envoi un boolean et que ce type n'a pas été pris en compte.

Je vous informerais de la mise en place d'un patch corrigeant cette anomalie.

Cordialement,

**Comment by hepr** [comment]
Bonsoir

Je suis en mode POST

Je passe par JSONStringify sinon j'avais les colonnes eclatées ou des object object.
Et sur le serveur je fais un json.parse.

Je peux regarder pourquoi mon parse  ne reconnais pas les boolean.

Merci de votre aide,

Herve

**Comment by hepr** [comment]
Je viens de faire le test en modifiant le fichier fields.js en ajoutant un
test sur le boolean et tout fonctionne parfaitement.

Voici ma correction :
line 83 return query[QUERY_COLUMNS][index][QUERY_SEARCHABLE_PREFIX] ==
'true' || query[QUERY_COLUMNS][index][QUERY_SEARCHABLE_PREFIX] === true;

et

line 85 return query[QUERY_COLUMNS][index][QUERY_SORTABLE_PREFIX] == 'true'
|| query[QUERY_COLUMNS][index][QUERY_SORTABLE_PREFIX] === true;

Merci pour ce module, il est genial

Herve


Herve Prot

President LE&CO
2 rue des Faubourgs
F-63960 Veyre-Monton
Tel : +33 6 76 76 17 65
herve.prot@leandco.fr

**Comment by eherve** [comment]
fixed with 07892e924556144cbad04c37673ed7770bc18bd5

**Comment by hepr** [comment]
Bonjour Eric,

je viens de faire un deploy de mon application et quand je fais un npm
install je tombe sur la version 1.0.0 de votre module et qui
malheureusement n'integre pas la derniere correction. Quand est prevue la
prochaine version ?

Merci

Herve

Herve Prot

President LE&CO
2 rue des Faubourgs
F-63960 Veyre-Monton
Tel : +33 6 76 76 17 65
herve.prot@leandco.fr

**Comment by eherve** [comment]
Bonjour Herve,

Effectivement la nouvelle version n'a pas encore été déployée sur le npm.
Cela étant du a un manque de temps pour les tests de mon côté, mais une
nouvelle version sera disponible fin de cette semaine normalement.

Je vous tiendrais informé quand elle sera publiée.
Le lun. 20 avr. 2015 à 06:31, Herve Prot <notifications@github.com> a
écrit :

> Bonjour Eric,
>
> je viens de faire un deploy de mon application et quand je fais un npm
> install je tombe sur la version 1.0.0 de votre module et qui
> malheureusement n'integre pas la derniere correction. Quand est prevue la
> prochaine version ?
>
> Merci
>
> Herve
>
> Herve Prot
>
> President LE&CO
> 2 rue des Faubourgs
> F-63960 Veyre-Monton
> Tel : +33 6 76 76 17 65
> herve.prot@leandco.fr
>
>

**Comment by hepr** [comment]
Bonjour Eric,

j'ai suis tombe sur un autre bug pour la meme raison du au POST.

Dans le fichier searchBuilder.js

Voici mes corrections en fin de fichier :

function isSearchRegexp() {
  return query[QUERY_SEARCH][QUERY_SEARCH_REGEXP] == 'true' ||
query[QUERY_SEARCH][QUERY_SEARCH_REGEXP] === true;
}

function isChunkSearch() {
  return query[QUERY_CHUNK_SEARCH] == 'true' || query[QUERY_CHUNK_SEARCH]
=== true;
}

function isSearchFieldRegexp(index) {
  return
query[QUERY_COLUMNS][index][QUERY_SEARCH][QUERY_SEARCH_REGEXP_PREFIX] ==
'true' ||
query[QUERY_COLUMNS][index][QUERY_SEARCH][QUERY_SEARCH_REGEXP_PREFIX] ===
true;
}

Bien a vous

Herve

Herve Prot

President LE&CO
2 rue des Faubourgs
F-63960 Veyre-Monton
Tel : +33 6 76 76 17 65
herve.prot@leandco.fr

**Comment by eherve** [comment]
Merci j'interprète cela ce soir et je dépose la nouvelle version sur NPM
dans la foulée.



Le jeu. 23 avr. 2015 à 09:49, Herve Prot <notifications@github.com> a
écrit :

> Bonjour Eric,
>
> j'ai suis tombe sur un autre bug pour la meme raison du au POST.
>
> Dans le fichier searchBuilder.js
>
> Voici mes corrections en fin de fichier :
>
> function isSearchRegexp() {
> return query[QUERY_SEARCH][QUERY_SEARCH_REGEXP] == 'true' ||
> query[QUERY_SEARCH][QUERY_SEARCH_REGEXP] === true;
> }
>
> function isChunkSearch() {
> return query[QUERY_CHUNK_SEARCH] == 'true' || query[QUERY_CHUNK_SEARCH]
> === true;
> }
>
> function isSearchFieldRegexp(index) {
> return
> query[QUERY_COLUMNS][index][QUERY_SEARCH][QUERY_SEARCH_REGEXP_PREFIX] ==
> 'true' ||
> query[QUERY_COLUMNS][index][QUERY_SEARCH][QUERY_SEARCH_REGEXP_PREFIX] ===
> true;
> }
>
> Bien a vous
>
> Herve
>
> Herve Prot
>
> President LE&CO
> 2 rue des Faubourgs
> F-63960 Veyre-Monton
> Tel : +33 6 76 76 17 65
> herve.prot@leandco.fr
>
>

**Comment by hepr** [comment]
J'ai une question,

dans ma requete sur je peux mettre des options

options :
- conditions
- select

condition doit correspondre a $match en debut de requete aggregate si j'ai
bien tout compris, mais a quoi correspond select ? Auriez-vous un exemple
d'utilisation de ces 2 parametres ?

Merci

Herve


Herve Prot

President LE&CO
2 rue des Faubourgs
F-63960 Veyre-Monton
Tel : +33 6 76 76 17 65
herve.prot@leandco.fr

**Comment by eherve** [comment]
Bonjour,

La nouvelle version est disponible sur le npm.
Concernant les options conditions et select:
* conditions sert à ajouter manuellement des filtres sur les résultats si on veut restreindre les éléments disponible par la recherche. Par exemple filtrer sur un groupe d'utilisateur ou un type d’objet...
* select sert à ajouter des champs remonté par la recherche, même si ceux-la ne sont pas présent dans la query de DataTable. Par exemple remonter si l'utilisateur est administrateur même si la query ne le demande pas (gestion d'affichage...)

Eric
