### ISSUE TITLE
searchBuilder.js has some bug.

### ISSUE THREAD

**Issue by taeminlee** [eherve/mongoose-datatable#30]
I have used mongoose-datatable very well.
However, updated to version 1.0.1 broken my app.
Because `isSearchFieldRegexp` function in `searchBuilder.js` has code like..
```javascript
function isSearchFieldRegexp(index) {
  return query[QUERY_COLUMNS][index][QUERY_SEARCH][QUERY_SEARCH_REGEXP_PREFIX] === 'true' ||
    uery[QUERY_COLUMNS][index][QUERY_SEARCH][QUERY_SEARCH_REGEXP_PREFIX] === true;
}
```
but `uery` should be `query` like..
```javascript
function isSearchFieldRegexp(index) {
  return query[QUERY_COLUMNS][index][QUERY_SEARCH][QUERY_SEARCH_REGEXP_PREFIX] === 'true' ||
    query[QUERY_COLUMNS][index][QUERY_SEARCH][QUERY_SEARCH_REGEXP_PREFIX] === true;
}
```
Please fix this issue. Thank you.

**Comment by eherve** [comment]
Hi,

Thanks for using the plugin and thanks for the feedback !
I have updated the code and published the 1.0.2 on npm to fix this issue.

Regards
