### ISSUE TITLE
not working with mongoose 4.1.0

### ISSUE THREAD

**Issue by mayaa6** [eherve/mongoose-datatable#33]
It seems current version mongoose-datatable doesn't work with the latest version mongoose 4.1.0. Can somebody fix this?

**Comment by eherve** [comment]
Hi,

Thanks for using the module.
I just tested with mongoose 4.1.0 and it works fine on my environment.
Can you be more precise about the issue you have ?

Regards,

**Comment by eherve** [comment]
I close this issue, no reply
