### ISSUE TITLE
Nested object search

### ISSUE THREAD

**Issue by stavros-zavrakas** [eherve/mongoose-datatable#39]
I have a hidden column in datatables that I name it as 'tags'. The tags in my mongo is an array of strings:

```
[
    "tag1",
    "tag2"
]
```

I have a problem searching on the tags. I tried something like that without success:
https://datatables.net/examples/ajax/objects_subarrays.html

I tried to debug a bit the library but my time is limited. Is it a bug or is it something that I am missing from the documentation.

This is the datatables options:

```
    $(el).DataTable({
        'order': [
            [2, 'desc']
        ],
        'lengthMenu': [
            [25, 50, 100, -1],
            [25, 50, 100, 'All']
        ],
        'sAjaxSource': '/files/get/datatables',
        'bProcessing': true,
        'bServerSide': true,
        'columns': [{
            'mData': 'title'
        }, {
            'mData': 'description'
        }, {
            'mData': 'tags',
            'visible': false,
            'defaultContent': ''
        }]
    });
```

The search is working normally for the title and the description. Any ideas?

**Comment by eherve** [comment]
Hi,

Thanks for using this plugin.
Can you activate the debug on the plugin and send me the trace please.

Regards
