### ISSUE TITLE
How to set conditions?

### ISSUE THREAD

**Issue by ghost** [eherve/mongoose-datatable#46]
Hi,

How to set conditions?.....How i do this...., The documentation is little. I need set a many field type search  and i have many fields through population, eg:  { data: 'libreria.name',"defaultContent": "", width: '25%'}, i need search this field and others....Help.

Thanks.

**Comment by eherve** [comment]
Hi,

Sorry for the very late reply...

The module doesn't do any filtering or sorting on populate data.
The populate data are fetched after the root document is fetched so it is not possible with the actual implementation.

I hope you found a way arround to your needs.

Regards
