### ISSUE TITLE
Unmanaged condition on field type: ObjectId

### ISSUE THREAD

**Issue by scherke** [eherve/mongoose-datatable#48]
Hi there,

when i search for path "_id" the type is "ObjectId" but for it doesn't exist a Handler.
Is that intentional. 
I added myself a "objectIdHandler.js", because I want to search for ObjectId, is there any other possibility.

regards

**Comment by eherve** [comment]
Hi,

Yes there is no ObjectId search handler in the module.
Adding it on configuration is the right way to do it, I tag this issue for enhancement for later.

Thanks for using the plugin and for this feedback.

regards

**Comment by Tavethiya** [comment]
I have same requirement please do as soon as possible.
