### ISSUE TITLE
Query lookup another collection, if not found still return

### ISSUE THREAD

**Issue by willyprayogo26** [eherve/mongoose-datatable#61]
I want to ask, I want to query to join another collection. It's working. But, I want to handle if I can't found that object id in another collection and the reality it's still return data with value of field is null. Now, I don't want return that data if join/lookup/populate not found. How to solve this? Can you help me?

**Comment by eherve** [comment]
Hi,

Sorry for my very late reply...

I hope you found a solution to your problem.
You can solve this by adding conditions in the options parameter of the dataTable method to add $ne: null to the joined field.
